# EPICS IOC
org.phoebus.pv.ca/addr_list=127.0.0.1
org.phoebus.pv.ca/auto_addr_list=false

# Archiver Appliance
org.csstudio.trends.databrowser3/urls=pbraw://archiver-appliance.localhost:14924/retrieval
org.csstudio.trends.databrowser3/archives=pbraw://archiver-appliance.localhost:14924/retrieval

# Phoebus alarm
org.phoebus.applications.alarm/server=localhost:9092
org.phoebus.applications.alarm.logging.ui/service_uri=http://alarm-logger.localhost:14924

# Phoebus save-and-restore
org.phoebus.applications.saveandrestore.client/jmasar.service.url=http://save-restore.localhost:14924/save-restore/

# Phoebus Olog
org.phoebus.olog.es.api/olog_url=http://olog.localhost:14924/Olog
org.phoebus.olog.es.api/username=admin
org.phoebus.olog.es.api/password=adminPass
org.phoebus.logbook/logbook_factory=olog-es

# ChannelFinder
org.phoebus.channelfinder/serviceURL = http://channel-finder.localhost:14924/ChannelFinder
org.phoebus.channelfinder/username = admin
org.phoebus.channelfinder/password = adminPass
